apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-configmap
  namespace: admin
data:
  RABBITMQ_HOST: "rabbitmq-headless.rabbitmq"
  RABBITMQ_PORT: "5672"
  DB_HOST: "192.168.3.10"
  DB_PORT: "3306"
  GOOGLE_REDIRECT_URI: "https://capstone.studylink.click/api/integrations/google/callback"
  GITHUB_REPO_OWNER: "GachonCapstone4"
  GITHUB_REPO_NAME: "Capstone_Cluster"
  GITHUB_BRANCH: "main"
  GITHUB_YAML_BASE_PATH: "admin-manifest/job-manifest"
  K8S_JOB_NAMESPACE: "admin"
  ADMIN_MONITORING_GRAFANA_DASHBOARDS: >-
    [{"key":"rabbitmq","label":"RabbitMQ","url":"https://grafana.studylink.click/d/rabbitmq-capstone-v9/673ea40?orgId=1&from=now-1h&to=now&timezone=Asia%2FSeoul&refresh=30s&kiosk"}]
