apiVersion: batch/v1
kind: Job
metadata:
  name: diag-k8s
  namespace: admin
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"

spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        job-name: diag-k8s
    spec:
      serviceAccountName: job-runner-sa
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  job-name: diag-k8s
              topologyKey: kubernetes.io/hostname
      containers:
        - name: diag-tool
          image: suhannugul/capstonetest:latest
          args: [ "k8s" ]
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: job-configmap
            - secretRef:
                name: job-secret
          securityContext:
            capabilities:
              add: ["NET_RAW", "NET_ADMIN" ]
      restartPolicy: Never