apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: suhannugul/email-agent:1ad94bf2a62f1d330a461cf3a8118a48a47ee6e2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-configmap
