apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  revisionHistoryLimit: 5
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: suhannugul/email-agent:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-configmap
